### ISSUE TITLE
error on cookie driver

### ISSUE THREAD

**Issue by lucabecchetti** [NoelDeMartin/laravel-dusk-mocking#18] opened 2019-11-04 17:10 UTC
I always obtain: 

Invalid argument supplied for foreach()

On CookieDriver.php

**Comment by NoelDeMartin** [comment] 2019-11-04 19:03
Can you provide an example project where this issue is reproduced? I've been using the package and I haven't encountered this problem, so I need more context.

**Comment by lucabecchetti** [comment] 2019-11-05 14:11
Using the breakpoint, this method it's called twice:

`
protected function load()
{
$data = Cookie::get(self::COOKIE_NAME, '{"mocks":{},"fakes":{}}');
$data = json_decode($data, true);
foreach ($data['mocks'] as $facade => $serializedMock) {
$this->mocks[$facade] = $this->unserialize($serializedMock);
}
$this->fakes = $data['fakes'];
}
`

the first time Dusk-Mocking cookie is not set and I have no error, the second time, trying to decode cookie content does not work, this is the cookie content:

eyJpdiI6IjZqTFRybGl2VzRpM05pczNzak5SNEE9PSIsInZhbHVlIjoiWURzWnRCaUNYM0JMN1grZFpndWN1TElucTd1SHliaWhvcnB5SUQzVFpCbz0iLCJtYWMiOiI3ZmQyNmYzNDU5MWYzYmUxMDQ1NGViNzYwZTczMzRlOWI1MjI3ODM2ZTFkOTYwOTcwMzA1ZDJiZDE4Y2JiYWQwIn0%3D

Showed in developer tools of firefox, it seems that the content of the cookies is not a valid json.

@NoelDeMartin I HAVE THIS ISSUE ROUTING THE SITE NORMALLY FROM BROWSER: http://localhost:80800, OR RUNNING artisan dusk

**Comment by lucabecchetti** [comment] 2019-11-08 14:41
@NoelDeMartin ideas?

**Comment by NoelDeMartin** [comment] 2019-11-08 15:30
I think this looks very similar to issue #16, please take a look to the comments I wrote there.

I may be mistaken, but to me this sounds like an environment problem, because I cannot reproduce it. I'd be happy to help you, but I don't know how to reproduce that environment error.

Can you reproduce this problem in a new application and upload it to github so that I try to reproduce it locally?

**Comment by NoelDeMartin** [comment] 2019-11-13 17:21
I've created a sandbox project with tests running on github actions, so maybe you can try to reproduce your problem there to be sure it isn't an environment issue.

Check it out: [https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox/](https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox/)

**Comment by NoelDeMartin** [comment] 2020-02-22 08:46
I am closing this issue because I cannot reproduce it. Feel free to reopen it, or open a new one, if you can provide a way to reproduce it.

**Closed as completed by NoelDeMartin** 2020-02-22 08:46 UTC
