### ISSUE TITLE
CookiesDriver.php

### ISSUE THREAD

**Issue by rivardje** [NoelDeMartin/laravel-dusk-mocking#16] opened 2019-10-10 08:38 UTC
if cookie exists but docker container is recomposed, then 

`    protected function load()
    {
        $data = Cookie::get(self::COOKIE_NAME, '{"mocks":{},"fakes":{}}');
        $data = json_decode($data, true);
    }`

$data = null and you get an error.

by adding the following: 
`        if($data == null) {
            $data = [
                'mocks' => [],
                'fakes' => [],
            ];
        }
` 

you don't try to do a foreach on a null value and it works fine.

**Comment by rivardje** [comment] 2019-10-10 09:42
the essence of my issue is that there is no verification on a null $data which is a situation that has happened to me.

**Comment by NoelDeMartin** [comment] 2019-10-11 08:15
Hey thanks for reporting.

I can add the null check given that it doesn't hurt, but I'd like to understand better how is this happening. The `get` method from the Cookie facade already handles non-existent cookies, and returns the second argument to this function if a cookies is not set. Which means you can only get that error if the cookie is set with an invalid value.

Keeping that in mind, the problem is actually the cookie being set with an invalid value at some point. I'd like to understand and fix the root of the cause rather than doing the null check workaround.

You mention docker, but I also use docker and I haven't encountered this problem. I need more details to understand what's going on in you environment.

**Comment by rivardje** [comment] 2019-10-11 08:57
I will gladly offer some more details towards the issue I am facing. 

To reproduce the issue: Using a Linux Docker, Laravel Framework and php artisan. I am calling upon the `docker-compose up` feature, which includes the following commands: 
```
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
```
thus clearing all cookies infos/recognition/etc on the server side. 
Now creating the container and the Web server of my work the very first time, by logging in the first time, no issues. Cookies are then created. close the website and power off the containers. 

Then, by relaunching the containers with the `docker-compose up.` Remember, server side have been cleared, but the browser still has "previous cookies". This is when it fails because the cookie exists but has an unrecognized value inside thus the $data variable being null.

**Comment by NoelDeMartin** [comment] 2019-10-26 06:35
I see, in this case I think the problem is related with the browser you're using to execute the tests, isn't it? As far as I understand, each test should be an isolated browser environment, meaning that cookies are not persisted through tests. If you for example have a test checking that a cookie is created, if the code fails to create the cookie but a previous run of the test had created it, the test would incorrectly be successful.

Maybe this has something to do with the browser driver you're using? I would take a look at that, because if cookies are being persisted through test executions, you may have other issues. If you can't fix this for any reason, I guess the correct way to do it would to clear all the cookies in the `setUp` method of your tests. This is not only relevant to this package, but to the test environment that you're setting up in general.

Does this make sense?

**Comment by NoelDeMartin** [comment] 2019-11-13 17:22
I've created a sandbox project with tests running on github actions, so maybe you can try to reproduce your problem there to be sure it isn't an environment issue.

Check it out: [https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox/](https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox/)

**Comment by NoelDeMartin** [comment] 2020-02-22 08:47
I am closing this issue because I cannot reproduce it. Feel free to reopen it, or open a new one, if you can provide a way to reproduce it.

**Closed as completed by NoelDeMartin** 2020-02-22 08:47 UTC
