### ISSUE TITLE
fake storage class

### ISSUE THREAD

**Issue by lucabecchetti** [NoelDeMartin/laravel-dusk-mocking#9] opened 2019-02-15 11:26 UTC
How can i fake storage GCS, in unittest i use:

Storage::fake('gcs');

but:

$browser->fake(Storage::class, 'gcs')

seems not to work!

**Comment by NoelDeMartin** [comment] 2019-02-18 20:15
I've been trying to look into this but I switched to using alpine linux with docker some time ago and I can't get dusk tests to run in there, so I can't reproduce your problem yet. I'll get back to you when I can reproduce it!

**Comment by NoelDeMartin** [comment] 2019-02-21 20:35
After some time digging into the problem, I found the reason why this is not working. And that is because the `Storage` facade uses the `FilesystemManager`, which contains a reference to the `Application` instance and that cannot be serialized (among other things, because it has Closures). You can learn more about this in the "How does it work?" section of the readme in this repo.

I've been working on a fix for this, but the current implementation only works for the first test, and subsequent tests fail. I still have to find why is that happening. On the meantime, it should work if you set the `processIsolation` option for your phpunit tests to true.

**Comment by lucabecchetti** [comment] 2019-02-21 20:36
Oh ok... I understand! I wait for a fix.... thanks for a great work!

**Closed as completed** 2019-03-15 19:06 UTC

**Comment by NoelDeMartin** [comment] 2019-03-15 19:43
@lucabecchetti I just released a couple of version (compatible with dusk 4 and 5) fixing this, let me know if it works for you!

**Comment by lucabecchetti** [comment] 2019-03-16 12:22
Thanks! I’ll try it next week!

**Comment by lucabecchetti** [comment] 2019-03-20 16:44
@NoelDeMartin it works like a charm! Thanks!
