### ISSUE TITLE
Unable to Retrieve Mock for Mail Facade

### ISSUE THREAD

**Issue by jcrawford** [NoelDeMartin/laravel-dusk-mocking#7] opened 2018-04-17 15:39 UTC
I have implemented the code as in your README but I am getting the following error.

```Exception: Unable to retrieve mock for [Illuminate\Support\Facades\Mail].```

Here is the output from running the tests.

```
PHPUnit 7.1.3 by Sebastian Bergmann and contributors.

E....                                                               5 / 5 (100%)

Time: 7.78 seconds, Memory: 12.00MB

There was 1 error:

1) Tests\Browser\ContactTest::testPhoneNotRequired
Exception: Unable to retrieve mock for [Illuminate\Support\Facades\Mail].

/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/MockingProxy.php:50
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/tests/Browser/ContactTest.php:32
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/tests/Browser/ContactTest.php:33

ERRORS!
Tests: 5, Assertions: 9, Errors: 1.
```

Here is the stack trace from the logs.

```
[2018-04-17 15:37:55] local.ERROR: Only arrays and Traversables can be unpacked {"exception":"[object] (ErrorException(code: 0): Only arrays and Traversables can be unpacked at /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Controllers/MockingController.php:18)
[stacktrace]
#0 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Controllers/MockingController.php(18): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Only arrays and...', '/Users/jcrawfor...', 18, Array)
#1 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): NoelDeMartin\\LaravelDusk\\Http\\Controllers\\MockingController->mock()
#2 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(NoelDeMartin\\LaravelDusk\\Http\\Controllers\\MockingController), 'mock')
#3 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#4 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#5 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Middleware/SaveMocking.php(19): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): NoelDeMartin\\LaravelDusk\\Http\\Middleware\\SaveMocking->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Middleware/StartMocking.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): NoelDeMartin\\LaravelDusk\\Http\\Middleware\\StartMocking->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 {main}
"}
```

**Comment by NoelDeMartin** [comment] 2018-04-17 15:57
Seems like this line is failing and that's why the mock is not registered correctly: https://github.com/NoelDeMartin/laravel-dusk-mocking/blob/master/src/Http/Controllers/MockingController.php#L18

It's trying to unpack the `$arguments` variable and the error is `Only arrays and Traversables can be unpacked`. I don't understand how that is possible, because that variable should be initialized properly before calling that route here: https://github.com/NoelDeMartin/laravel-dusk-mocking/blob/master/src/Browser.php#L27

Try to do the following things to debug what's going on:
- What's you php version? Maybe that has something to do with this.
- Add this line `app('log')->info($arguments);` to both `MockingController.php` and `Browser.php` and run again to obtain the new logs (you can do that to the files under vendors/ and it should pick up the changes).

Let's see if we can find why that's happening. I'm thinking it has something to do with the environment and php, because maybe the unpacking syntax does not behave in the same way.

**Comment by jcrawford** [comment] 2018-04-17 16:06
@NoelDeMartin I am running PHP 7.1.13 

I have added the log calls as you requested, it appears to be an empty array and possibly null.

```
[2018-04-17 16:05:07] local.INFO: array (
)
[2018-04-17 16:05:07] local.INFO:
[2018-04-17 16:05:07] local.ERROR: Only arrays and Traversables can be unpacked {"exception":"[object] (ErrorException(code: 0): Only arrays and Traversables can be unpacked at /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Controllers/MockingController.php:19)
[stacktrace]
```

**Comment by NoelDeMartin** [comment] 2018-04-17 16:13
Ok, the first log makes sense, but I don't understand how it is possible to get the second one as null. If you look at the line calling the route, this is executed: `urlencode(json_encode($arguments))`. With that statement, the value for the `$arguments` variable once decoded should be an empty array, not null.

Can you log the value of the parameter before decoding the json? Add `app('log')->info(request('arguments'))` as the first line in the `MockingController.php` method.

**Comment by jcrawford** [comment] 2018-04-17 16:18
All I get is the following.

```
[2018-04-17 16:17:37] local.INFO: %5B%5D
```

When decoded that is ```[]```

**Comment by NoelDeMartin** [comment] 2018-04-17 16:29
Ok we found the problem! But I don't understand why this happens :/. `%5B%5D` is the url encoded value for `[]`, which is basically a json encoded empty array. The question here is why are you getting `%5B%5D` and not `[]` as your value for that request parameter... Seems like your laravel controller is not decoding the url parameters properly, and it's the first time I see that. It's likely to be due to the webdriver implementation or some environment specific issue. Can you tell me which webdriver are you using? If you don't know which one you are probably using the default configuration for dusk.

In any case, this should be fixed if you do the following. Change the line `$arguments = json_decode(request('arguments'));` for `$arguments = json_decode(urldecode(request('arguments')));` in the `MockingController` class. If that solves the problem, I will commit a fix for this until the webdriver bug is solved.

**Comment by jcrawford** [comment] 2018-04-17 16:42
I am using the default webdriver as I have not changed it.

That code change does not appear to work for me, now it logs the following

```
[2018-04-17 16:41:37] local.ERROR: Class 'Illuminate%5CSupport%5CFacades%5CMail' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Illuminate%5CSupport%5CFacades%5CMail' not found at /Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/Driver.php:143)
[stacktrace]
```

everything works if i urldecode the $facade variable as well though, very odd..

**Comment by jcrawford** [comment] 2018-04-17 16:50
Also, I am not sure if this is due to this library or Laravel itself, however, I have 3 tests that would return validation errors so no email would be sent when this is executed in the browser, however, the failed test says that the mailable is sent when it is not.

```
1) Tests\Browser\ContactTest::testNameIsRequired
The unexpected [App\Mail\Contact] mailable was sent.
Failed asserting that false is true.

/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:71
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/noeldemartin/laravel-dusk-mocking/src/MockingProxy.php:48
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/tests/Browser/ContactTest.php:69
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
/Users/jcrawford/Dropbox/CodeSamples/php-contact-form/tests/Browser/ContactTest.php:70
```

**Comment by NoelDeMartin** [comment] 2018-04-17 16:56
The first error is the same problem, seems like the class name is not being url decoded.

The second one is even weirder, because if all of this isn't working I don't understand how it is possible that you are getting that message. Did you add the `urldecode` to the other parameters to get this working?

I would suggest that you try using a different webdriver because I suspect this is a bug with that. Of course, I am not sure, but the fact that you are getting parameters without being decoded is super weird.

**Comment by jcrawford** [comment] 2018-04-17 17:00
yes to get the latest error I added decode to both arguments and facade.

which driver would you suggest I try?

**Comment by NoelDeMartin** [comment] 2018-04-17 17:02
I am using [selenium](https://docs.seleniumhq.org/), adding this to the `DuskTestCase` class:

```php
protected function driver()
{
    return RemoteWebDriver::create(
        'http://selenium:4444/wd/hub', DesiredCapabilities::chrome()
    );
}
```

**Comment by jcrawford** [comment] 2018-04-17 17:03
Ahh, this is for a code sample I cannot expect them to spin up a selenium server to run the tests.

**Comment by NoelDeMartin** [comment] 2018-04-17 18:25
I will try to implement this with a different approach using Javascript to post requests (similar to what I did here: 3f454d35de792fd5e990d38075259b6bfb4a3e2c). Although this issue is not inherently related with this extension, I think that approach would also be better to handle exceptions, which are not being handled at the moment.

I'll keep this issue open until I do that.

**Comment by jcrawford** [comment] 2018-04-18 14:28
Once you get this done I will run a test and let you know if all is working on my end.

**Comment by NoelDeMartin** [comment] 2018-04-24 19:47
@jcrawford I just pushed a couple of commits migrating to post requests using javascript, so your problem should be fixed. Let me know if it works.

**Comment by NoelDeMartin** [comment] 2018-05-02 09:53
It should be fixed now, so I'll close this issue.

**Closed as completed by NoelDeMartin** 2018-05-02 09:53 UTC

**Comment by ngzax** [comment] 2020-10-10 21:17
Hi, Thanks for creating this library. I think it is exactly what I need. However, it doesn’t seem to be working for me.

I added the use and the method to DuskTestCase and the new config file. I have the following test, which would normally send an email to the user, which is what I am trying to test:

```
public function testTwoFactorAuthRejectsInvalidVerificationCode() {
    $this->browse(function ($browser) {
      $mail = $browser->fake(Mail::class);

      $browser->visit('/login')
              ->type('input[name="email"]',    $this->userName)
              ->type('input[name="password"]', $this->Password)
              ->click('button[type="submit"]')
              ->pause(1000);

              $mail->assertSent(TwoFactorCode::class);
    });
}
```

unfortunately I am now facing this exact same issue. [PHP 7.3, Laravel 6.18.42. laravel-dusk-mocking 6.5.1]

```
Authentication (Tests\Browser\Authentication)
 ✘ Two factor auth rejects invalid verification code  3502 ms
   ┐
   ├ Exception: Unable to retrieve mock for [Illuminate\Support\Facades\Mail].
   │
   ╵ /Users/ngzax/Code/dc/decios/dc/vendor/noeldemartin/laravel-dusk-mocking/src/MockingProxy.php:50
   ╵ /Users/ngzax/Code/dc/decios/dc/tests/browser/AuthenticationTest.php:144
   ╵ /Users/ngzax/Code/dc/decios/dc/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:68
   ╵ /Users/ngzax/Code/dc/decios/dc/tests/browser/AuthenticationTest.php:155
```

**Comment by NoelDeMartin** [comment] 2020-10-12 07:29
Hi there @ngzax,

That should work, I don't see any problems with your code. I think you'll have to debug if you want to see what's going on :/, the management of mock instances happens within the `Driver.php` file, so you'll be able to find that in `vendor/noeldemartin/laravel-dusk-mocking/src/Driver.php` in your project. Keep in mind that this code is executed server-side, so you won't be able to see the output in your tests if you use `dd` or `var_dump`. What I usually do to debug this is writing to log files.

Alternatively, there is [a sandbox project](https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox) running tests in a CI environment. Maybe you can compare your configuration with that project to see if something's different. You can also try forking it and reproducing your bug there, but there is already [a test](https://github.com/NoelDeMartin/laravel-dusk-mocking-sandbox/blob/master/tests/Browser/ExampleTest.php#L20..L32) that is almost identical to yours and it works.

**Comment by ngzax** [comment] 2020-10-12 13:23
Thanks for the detailed reply and thanks for being such a responsible project owner, it's appreciated. :)

I will look into sandbox config and add some logging to the Driver.php and let you know.
